#pragma once

// PUBGm GL/KR/VN/TW - 64bit (4.5.0) SDK by BangJO [Z] DM @isar_hackJO To Buy Tool SDK

#include "PUBGM_BangJO.hpp"

namespace SDK
{
//---------------------By BangJO---------------------------
//Parameters
//---------------------By BangJO---------------------------

// Function CH_Base_AnimBP_MainCity_HoldingHands_F.CH_Base_AnimBP_MainCity_HoldingHands_F_C.EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_HoldingHands_F_AnimGraphNode_BlendListByBool_B2BE1E12445F893020F9FC852C1CBEFB
struct UCH_Base_AnimBP_MainCity_HoldingHands_F_C_EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_HoldingHands_F_AnimGraphNode_BlendListByBool_B2BE1E12445F893020F9FC852C1CBEFB_Params
{
};

// Function CH_Base_AnimBP_MainCity_HoldingHands_F.CH_Base_AnimBP_MainCity_HoldingHands_F_C.EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_HoldingHands_F_AnimGraphNode_BlendListByEnumAdvance_3A2038614D53C950AE7A438A48E15D1C
struct UCH_Base_AnimBP_MainCity_HoldingHands_F_C_EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_HoldingHands_F_AnimGraphNode_BlendListByEnumAdvance_3A2038614D53C950AE7A438A48E15D1C_Params
{
};

// Function CH_Base_AnimBP_MainCity_HoldingHands_F.CH_Base_AnimBP_MainCity_HoldingHands_F_C.EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_HoldingHands_F_AnimGraphNode_BlendSpacePlayer_36EFF0AD455D1087D005EE9679924173
struct UCH_Base_AnimBP_MainCity_HoldingHands_F_C_EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_HoldingHands_F_AnimGraphNode_BlendSpacePlayer_36EFF0AD455D1087D005EE9679924173_Params
{
};

// Function CH_Base_AnimBP_MainCity_HoldingHands_F.CH_Base_AnimBP_MainCity_HoldingHands_F_C.EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_HoldingHands_F_AnimGraphNode_TwoBoneIK_6681A6DF4BEFD2E65514B48983986CE9
struct UCH_Base_AnimBP_MainCity_HoldingHands_F_C_EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_HoldingHands_F_AnimGraphNode_TwoBoneIK_6681A6DF4BEFD2E65514B48983986CE9_Params
{
};

// Function CH_Base_AnimBP_MainCity_HoldingHands_F.CH_Base_AnimBP_MainCity_HoldingHands_F_C.EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_HoldingHands_F_AnimGraphNode_Fabrik_A46E136942B80F2789AD22A01DE63E68
struct UCH_Base_AnimBP_MainCity_HoldingHands_F_C_EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_HoldingHands_F_AnimGraphNode_Fabrik_A46E136942B80F2789AD22A01DE63E68_Params
{
};

// Function CH_Base_AnimBP_MainCity_HoldingHands_F.CH_Base_AnimBP_MainCity_HoldingHands_F_C.EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_HoldingHands_F_AnimGraphNode_SimpleIKSolver_B3D0F9F94CC22A1FF16EACAF430D5378
struct UCH_Base_AnimBP_MainCity_HoldingHands_F_C_EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_HoldingHands_F_AnimGraphNode_SimpleIKSolver_B3D0F9F94CC22A1FF16EACAF430D5378_Params
{
};

// Function CH_Base_AnimBP_MainCity_HoldingHands_F.CH_Base_AnimBP_MainCity_HoldingHands_F_C.EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_HoldingHands_F_AnimGraphNode_BlendSpacePlayer_0B7D5B7F48E055EF1F9D0F9D519D10B7
struct UCH_Base_AnimBP_MainCity_HoldingHands_F_C_EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_HoldingHands_F_AnimGraphNode_BlendSpacePlayer_0B7D5B7F48E055EF1F9D0F9D519D10B7_Params
{
};

// Function CH_Base_AnimBP_MainCity_HoldingHands_F.CH_Base_AnimBP_MainCity_HoldingHands_F_C.ExecuteUbergraph_CH_Base_AnimBP_MainCity_HoldingHands_F
struct UCH_Base_AnimBP_MainCity_HoldingHands_F_C_ExecuteUbergraph_CH_Base_AnimBP_MainCity_HoldingHands_F_Params
{
	int EntryPoint; // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

