#pragma once

// PUBGm GL/KR/VN/TW - 64bit (4.5.0) SDK by BangJO [Z] DM @isar_hackJO To Buy Tool SDK

#include "PUBGM_BangJO.hpp"

namespace SDK
{
//---------------------By BangJO---------------------------
//Parameters
//---------------------By BangJO---------------------------

// Function CH_Base_AnimBP_MainCity_CarryBack_Close.CH_Base_AnimBP_MainCity_CarryBack_Close_C.EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_CarryBack_Close_AnimGraphNode_BlendSpaceEvaluator_6F97B27C4867FA6D491617A1EF887AA3
struct UCH_Base_AnimBP_MainCity_CarryBack_Close_C_EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_CarryBack_Close_AnimGraphNode_BlendSpaceEvaluator_6F97B27C4867FA6D491617A1EF887AA3_Params
{
};

// Function CH_Base_AnimBP_MainCity_CarryBack_Close.CH_Base_AnimBP_MainCity_CarryBack_Close_C.EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_CarryBack_Close_AnimGraphNode_BlendSpaceEvaluator_4786E5964EF0BA870C8A40A5A0A738E4
struct UCH_Base_AnimBP_MainCity_CarryBack_Close_C_EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_CarryBack_Close_AnimGraphNode_BlendSpaceEvaluator_4786E5964EF0BA870C8A40A5A0A738E4_Params
{
};

// Function CH_Base_AnimBP_MainCity_CarryBack_Close.CH_Base_AnimBP_MainCity_CarryBack_Close_C.EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_CarryBack_Close_AnimGraphNode_BlendSpaceEvaluator_758B5B104911D34782C46DACD33A10B8
struct UCH_Base_AnimBP_MainCity_CarryBack_Close_C_EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_CarryBack_Close_AnimGraphNode_BlendSpaceEvaluator_758B5B104911D34782C46DACD33A10B8_Params
{
};

// Function CH_Base_AnimBP_MainCity_CarryBack_Close.CH_Base_AnimBP_MainCity_CarryBack_Close_C.EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_CarryBack_Close_AnimGraphNode_BlendListByEnumAdvance_328EB8B6403AA8F5F59E35A268C38C94
struct UCH_Base_AnimBP_MainCity_CarryBack_Close_C_EvaluateGraphExposedInputs_ExecuteUbergraph_CH_Base_AnimBP_MainCity_CarryBack_Close_AnimGraphNode_BlendListByEnumAdvance_328EB8B6403AA8F5F59E35A268C38C94_Params
{
};

// Function CH_Base_AnimBP_MainCity_CarryBack_Close.CH_Base_AnimBP_MainCity_CarryBack_Close_C.BpOnDeactived
struct UCH_Base_AnimBP_MainCity_CarryBack_Close_C_BpOnDeactived_Params
{
};

// Function CH_Base_AnimBP_MainCity_CarryBack_Close.CH_Base_AnimBP_MainCity_CarryBack_Close_C.BpOnActived
struct UCH_Base_AnimBP_MainCity_CarryBack_Close_C_BpOnActived_Params
{
};

// Function CH_Base_AnimBP_MainCity_CarryBack_Close.CH_Base_AnimBP_MainCity_CarryBack_Close_C.ExecuteUbergraph_CH_Base_AnimBP_MainCity_CarryBack_Close
struct UCH_Base_AnimBP_MainCity_CarryBack_Close_C_ExecuteUbergraph_CH_Base_AnimBP_MainCity_CarryBack_Close_Params
{
	int EntryPoint; // (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData)
};

}

