std::string JSON_ITEMS = "[\n"
                         "  {\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 101001,\n"
                         "        \"itemClass\": \"BP_Rifle_AKM_Wrapper_C_1\",\n"
                         "        \"itemName\": \"AKM\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101002,\n"
                         "        \"itemClass\": \"BP_Rifle_M16A4_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M16A4\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 101003,\n"
                         "        \"itemClass\": \"BP_Rifle_SCAR_Wrapper_C_1\",\n"
                         "        \"itemName\": \"SCAR-L\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101004,\n"
                         "        \"itemClass\": \"BP_Rifle_M416_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M416\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 101005,\n"
                         "        \"itemClass\": \"BP_Rifle_Groza_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Groza\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 101007,\n"
                         "        \"itemClass\": \"BP_Rifle_QBZ_Wrapper_C_1\",\n"
                         "        \"itemName\": \"QBZ\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 101008,\n"
                         "        \"itemClass\": \"BP_Rifle_M762_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M762\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 105001,\n"
                         "        \"itemClass\": \"BP_Other_M249_Wrapper_C_1\",\n"
                         "        \"itemName\": \"M249\",\n"
                         "        \"itemTextColor\": \"0xFFD1EEEE\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 105002,\n"
                         "        \"itemClass\": \"BP_Other_DP28_Wrapper_C_1\",\n"
                         "        \"itemName\": \"DP-28\",\n"
                         "        \"itemTextColor\": \"0xFFFCC89D\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 102001,\n"
                         "        \"itemClass\": \"BP_MachineGun_Uzi_Wrapper_C_1\",\n"
                         "        \"itemName\": \"UZI\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 102002,\n"
                         "        \"itemClass\": \"BP_MachineGun_UMP9_Wrapper_C_1\",\n"
                         "        \"itemName\": \"UMP45\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 102003,\n"
                         "        \"itemClass\": \"BP_MachineGun_Vector_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Vector\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  },\n"
                         "  {\n"
                         "    \"Items\": [\n"
                         "      {\n"
                         "        \"itemId\": 102004,\n"
                         "        \"itemClass\": \"BP_MachineGun_TommyGun_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Tompson SMG\",\n"
                         "        \"itemTextColor\": \"0xFFF8FAB9\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 102005,\n"
                         "        \"itemClass\": \"BP_MachineGun_PP19_Wrapper_C_1\",\n"
                         "        \"itemName\": \"PP-19 Bizon\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 102007,\n"
                         "        \"itemClass\": \"BP_MachineGun_MP5K_Wrapper_C_1\",\n"
                         "        \"itemName\": \"Skorpion\",\n"
                         "        \"itemTextColor\": \"0xFF919AFF\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601001,\n"
                         "        \"itemClass\": \"Drink_Pickup_C_1\",\n"
                         "        \"itemName\": \"Energy Drink\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601002,\n"
                         "        \"itemClass\": \"Injection_Pickup_C_1\",\n"
                         "        \"itemName\": \"Adrenaline Syringe\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601003,\n"
                         "        \"itemClass\": \"Pills_Pickup_C_1\",\n"
                         "        \"itemName\": \"Painkiller\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601004,\n"
                         "        \"itemClass\": \"Bandage_Pickup_C_1\",\n"
                         "        \"itemName\": \"Bandage\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601005,\n"
                         "        \"itemClass\": \"Firstaid_Pickup_C_1\",\n"
                         "        \"itemName\": \"First Aid Kit\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      },\n"
                         "      {\n"
                         "        \"itemId\": 601006,\n"
                         "        \"itemClass\": \"FirstAidbox_Pickup_C_1\",\n"
                         "        \"itemName\": \"Med Kit\",\n"
                         "        \"itemTextColor\": \"0xFF4DFF76\",\n"
                         "        \"itemOutlineColor\": \"0xFF000000\"\n"
                         "      }\n"
                         "    ]\n"
                         "  }\n"
                         "]";